#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Function Declarations */
void createFile();
void writeFile();
void readFile();
void deleteFile();
void renameFile();
void copyFile();
void showDateTime();
void calculator();

int main() {
    int choice;

        while (1) {
                printf("\n========== MINI OPERATING SYSTEM ==========\n");
                        printf("1. Create File\n");
                                printf("2. Write to File\n");
                                        printf("3. Read File\n");
                                                printf("4. Delete File\n");
                                                        printf("5. Rename File\n");
                                                                printf("6. Copy File\n");
                                                                        printf("7. Show Date & Time\n");
                                                                                printf("8. Calculator\n");
                                                                                        printf("9. Exit\n");
                                                                                                printf("===========================================\n");
                                                                                                        printf("Enter your choice: ");
                                                                                                                scanf("%d", &choice);

                                                                                                                        switch (choice) {
                                                                                                                                    case 1: createFile(); break;
                                                                                                                                                case 2: writeFile(); break;
                                                                                                                                                            case 3: readFile(); break;
                                                                                                                                                                        case 4: deleteFile(); break;
                                                                                                                                                                                    case 5: renameFile(); break;
                                                                                                                                                                                                case 6: copyFile(); break;
                                                                                                                                                                                                            case 7: showDateTime(); break;
                                                                                                                                                                                                                        case 8: calculator(); break;
                                                                                                                                                                                                                                    case 9:
                                                                                                                                                                                                                                                    printf("Exiting Mini OS...\n");
                                                                                                                                                                                                                                                                    exit(0);
                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                printf("Invalid choice! Try again.\n");
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                /* Create File */
                                                                                                                                                                                                                                                                                                                void createFile() {
                                                                                                                                                                                                                                                                                                                    FILE *fp;
                                                                                                                                                                                                                                                                                                                        char filename[50];

                                                                                                                                                                                                                                                                                                                            printf("Enter file name: ");
                                                                                                                                                                                                                                                                                                                                scanf("%s", filename);

                                                                                                                                                                                                                                                                                                                                    fp = fopen(filename, "w");
                                                                                                                                                                                                                                                                                                                                        if (fp == NULL) {
                                                                                                                                                                                                                                                                                                                                                printf("File creation failed!\n");
                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                            printf("File created successfully!\n");
                                                                                                                                                                                                                                                                                                                                                                    fclose(fp);
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        /* Write to File */
                                                                                                                                                                                                                                                                                                                                                                        void writeFile() {
                                                                                                                                                                                                                                                                                                                                                                            FILE *fp;
                                                                                                                                                                                                                                                                                                                                                                                char filename[50], data[200];

                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter file name: ");
                                                                                                                                                                                                                                                                                                                                                                                        scanf("%s", filename);

                                                                                                                                                                                                                                                                                                                                                                                            fp = fopen(filename, "a");
                                                                                                                                                                                                                                                                                                                                                                                                if (fp == NULL) {
                                                                                                                                                                                                                                                                                                                                                                                                        printf("Unable to open file!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Enter data (end with #):\n");
                                                                                                                                                                                                                                                                                                                                                                                                                            getchar(); // clear buffer
                                                                                                                                                                                                                                                                                                                                                                                                                                while (1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        fgets(data, 200, stdin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (strchr(data, '#')) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fputs(data, fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                fclose(fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Data written successfully!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* Read File */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    void readFile() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FILE *fp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char filename[50], ch;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Enter file name: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%s", filename);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fp = fopen(filename, "r");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (fp == NULL) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("File not found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("\n--- File Content ---\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while ((ch = fgetc(fp)) != EOF) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                putchar(ch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fclose(fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Delete File */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void deleteFile() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char filename[50];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Enter file name to delete: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%s", filename);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (remove(filename) == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("File deleted successfully!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Unable to delete file!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* Rename File */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void renameFile() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                char oldname[50], newname[50];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter old file name: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        scanf("%s", oldname);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Enter new file name: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scanf("%s", newname);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (rename(oldname, newname) == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("File renamed successfully!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Rename failed!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Copy File */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void copyFile() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FILE *src, *dest;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                char source[50], target[50], ch;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter source file: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        scanf("%s", source);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Enter target file: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scanf("%s", target);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src = fopen(source, "r");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dest = fopen(target, "w");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (src == NULL || dest == NULL) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("File error!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while ((ch = fgetc(src)) != EOF) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fputc(ch, dest);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fclose(src);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fclose(dest);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("File copied successfully!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* Date & Time */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void showDateTime() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                time_t t;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    time(&t);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Current Date & Time: %s", ctime(&t));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Calculator */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void calculator() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int a, b, ch;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("\nCalculator\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("1. Add\n2. Subtract\n3. Multiply\n4. Divide\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Enter choice: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            scanf("%d", &ch);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Enter two numbers: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%d%d", &a, &b);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        switch (ch) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 1: printf("Result = %d\n", a + b); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 2: printf("Result = %d\n", a - b); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 3: printf("Result = %d\n", a * b); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (b != 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Result = %d\n", a / b);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Division by zero not allowed!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Invalid option!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } 